//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autopark1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class auto_parkEntities : DbContext
    {
        public auto_parkEntities()
            : base("name=auto_parkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Аренда> Аренда { get; set; }
        public virtual DbSet<Водители> Водители { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Маршруты> Маршруты { get; set; }
        public virtual DbSet<Остановки> Остановки { get; set; }
        public virtual DbSet<Остановки_Маршруты> Остановки_Маршруты { get; set; }
        public virtual DbSet<Платежи> Платежи { get; set; }
        public virtual DbSet<Продажи> Продажи { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Услуги_По_Обслуживанию> Услуги_По_Обслуживанию { get; set; }
    }
}
