//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autopark1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Водители
    {
        public int ID_Водителя { get; set; }
        public string ФИО { get; set; }
        public int ID_Маршрута { get; set; }
        public string Номер_ВУ { get; set; }
        public string Телефон { get; set; }
    
        public virtual Маршруты Маршруты { get; set; }
    }
}
