//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autopark1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршруты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Маршруты()
        {
            this.Водители = new HashSet<Водители>();
            this.Остановки_Маршруты = new HashSet<Остановки_Маршруты>();
        }
    
        public int ID_Маршрута { get; set; }
        public int ID_Клиента { get; set; }
        public int ID_Остановки { get; set; }
        public string Название_Маршрута { get; set; }
        public string Начальная_Точка { get; set; }
        public string Конечная_Точка { get; set; }
        public string Расстояние { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Водители> Водители { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Остановки_Маршруты> Остановки_Маршруты { get; set; }
    }
}
