//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autopark1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Остановки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Остановки()
        {
            this.Остановки_Маршруты = new HashSet<Остановки_Маршруты>();
        }
    
        public int ID_Остановки { get; set; }
        public int ID_Клиента { get; set; }
        public string Название_Остановки { get; set; }
        public string Местоположение { get; set; }
        public System.DateTime Время_Прибытия { get; set; }
        public System.DateTime Время_Отправления { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Остановки_Маршруты> Остановки_Маршруты { get; set; }
    }
}
