//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autopark1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платежи
    {
        public int ID_Платежа { get; set; }
        public int ID_Сотрудника { get; set; }
        public int ID_Клиента { get; set; }
        public string Сумма { get; set; }
        public System.DateTime Дата_Платежа { get; set; }
        public string Номер_Счета { get; set; }
        public string Метод_Оплаты { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
