//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autopark1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги_По_Обслуживанию
    {
        public int ID_Услуги { get; set; }
        public int ID_Автомобиля { get; set; }
        public string Название_Услуги { get; set; }
        public System.DateTime Дата_Начала_Работ { get; set; }
        public System.DateTime Дата_Окончания_Работ { get; set; }
        public int Цена { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
    }
}
